### PR TITLE
Added method to get accounts as an admin

### PR DESCRIPTION
**Pull request by mancku**
This PR contains the new entity and the new partial class needed to get the accounts as an admin.

### CODE REVIEW

**Comment by glacasa** [comment]
Thanks for the PR ! sorry for the delay, I think I just missed the notif e-mail.
I'm going to look at that

**Comment by mancku** [comment]
Thanks @glacasa! Let me know if you need me to clarify or modify something

**Comment by glacasa** [comment]
I updated the code to match with the Mastodon docs 
https://github.com/glacasa/Mastonet/commit/c597878e8deb78603ef9d614750fc5e99ff60fca

I don't have an admin mastodon account to test, could you check if I didn't break anything ?

It's on Nuget if you want to try
https://www.nuget.org/packages/Mastonet/2.2.2-preview-adminapi

(side note : are from Catalunya ? I'm in Ariège, just on the other side of the french border 👋)

**Comment by ctrl-alt-d** [comment]
Hi @glacasa, Comment ça va? I just tested this branch against our Mastodon node, using admin token credentials, and it runs like a charm.

(side note : yes, we are from Catalunya. Best regards from this side of the border 👋)

**Comment by glacasa** [comment]
Totally ok to have better code 👍
What parts exactly would you refactor ?

**Comment by mancku** [comment]
Some things that came to my mind while adding the Admin classes:
* In BaseHttpClient I would unify some methods to re-use code. 
* I'd apply the new AddQueryStringParam method to the current code that could benefit from it.
* Almost everywhere in the code variables are declared with var, but in some places explicit type is being used instead. I'd change that to var.
* Following the previous one, I'd like to add a .editorconfig file so the styles are defined in the solution

**Pull request merged**
