### PR TITLE
[DRAFT] Updated the Post() method so that it doesn't hang when used in Avalonia projects

### PR DESCRIPTION
**Pull request by benpocalypse**
I realize I've intertwined `await` with `GetAwaiter().GetResult()` but that seemed to be the magic that makes this work. Feel free to suggest changes or reject my PR if this isn't an acceptable solution.

### CODE REVIEW

**Comment by benpocalypse** [comment]
As I've been progressing, I've found other functions that seem to not play nice with Avalonia. I'm going to mark this as Draft until I work out some more kinks.

**Comment by glacasa** [comment]
I'd rather avoid the `GetAwaiter().GetResult()`
Do you have a sample Avalonia project I could look at ?

**Comment by benpocalypse** [comment]
Yeah, I probably jumped the gun a bit by creating a PR for this.

I have a working example of the bug here: https://github.com/benpocalypse/MastodonAvaloniaTestg

In MainWindow.xaml.cs, the program will hang forever on line 15.

Let me know what you think - and thanks again for this awesome library.

**Comment by benpocalypse** [comment]
Apologies for the delay in circling back on this - been a busy week or two.

I'm convinced after trying this with a couple different UI libraries that this is an Avalonia problem and not a Mastonet problem, so I'm going to close this PR.

**Pull request closed without merging**
